### PR TITLE
(MODULES-6472) - Implementing Rubocop

### PR DESCRIPTION
**Pull request by pmcmaw**
The baseline version of rubocop that has been used is 0.49.1.
This is prep for running `pdk convert` on this module.

### CODE REVIEW

**Comment by pmcmaw** [comment]
@david22swan Can I get a review on this please.

**Comment by tphoney** [comment]
Looks good to me, however i would like @shermdog to look over the changes too. This has the possibility to have far reaching implications.

**Comment by shermdog** [comment]
We'll have to do some digging into these changes to make sure they don't break anything in modules that consume this.

Of particular note need to see if anyone is overriding ```is_to_s``` and if the title pattern changes break anything.

We'll be releasing an updated Cisco Nexus module very soon, so we also need to decide if we bump the version of this module prior or post that.

**Comment by pmcmaw** [comment]
Cool @shermdog, if this one in particular is making you feel nervous I can just go ahead `disable` this specific rule by default in order to avoid any risk at all.

**Comment by pmcmaw** [comment]
Closing as this has been lying around for a while and has lots of conflicts.

**Pull request closed without merging**
