### PR TITLE
(MODULES-8161) netdev provider to forward calls to correct provider

### PR DESCRIPTION
**Pull request by Thomas-Franklin**

### CODE REVIEW

**Comment by da-ar** [comment]
+1

**Comment by da-ar** [comment]
@Thomas-Franklin Your commit on this PR will need renamed

**Comment by willmeek** [comment]
Does it run successfully against Cisco IOS? Thanks

**Comment by da-ar** [comment]
> Does it run successfully against Cisco IOS? Thanks

I'm using this PR in the manual tests I'm running with IOS + NEXUS

**Pull request merged**
